import "@/styles/globals.css";
import { Inter as FontSans } from "next/font/google";

import { GeistSans } from "geist/font/sans";
import { cn } from "@/lib/utils";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        "bg-background min-h-screen font-sans antialiased",
        fontSans.variable,
        GeistSans.variable,
      )}
    >
      <body>{children}</body>
    </html>
  );
}
